id: PC4A86F95
initial_creation_type: ocr
source_metadata:
  volumes:
    fec9e72afeb745f0b59911d1033888bb:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: ཕྱག་འཚལ་བའི་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
